my_string = input("Введите строку: ")
print("В строке символов: ", len(my_string))
print("Строка в верхнем регистре")
print(my_string.upper())
print("Строка в нижнем регистре")
print(my_string.lower())
print("Строка без пробелов")
print(my_string.replace(" ",""))
print(my_string[0])
print(my_string[-1])